fix: add cache to gitignore
csicsi2000/PTI-Books-app pull request #15
Opened 2023-04-02 14:50 UTC by csicsi2000

2023-04-02 17:19 UTC, csik-patrik commented
Szia! a .gitignore fileba is bele kell írni, úgy veszi figyelmen kívül a git.

2023-04-02 17:22 UTC, csik-patrik requested changes
Elérési útvonal hozzáadása a .gitignore fileba

2023-04-09 06:42 UTC, csicsi2000 commented
Szia, a gitignoreba hozzá volt már adva csak azután hogy létre jött a fájl, így trackelte.
[fájl helye]( https://github.com/csicsi2000/PTI-Books-app/blob/gitignore_extend/app/frontend/.gitignore)

2023-04-12 16:30 UTC, csicsi2000 commented
updateltem és kitöröltem a gitignorokat

2023-04-13 16:29 UTC, csik-patrik approved these changes

2023-04-13 16:30 UTC, merged